### PR TITLE
feat: add hazelcast kubernetes discovery plugin

### PR DESCRIPTION
**Pull request by cschockaert**
add hazelcast kubernetes autodiscovery plugin:

modify your hazelcast.xml this way:

```
 <network>
        <port auto-increment="true">5701</port>
        <join>
            <!--<multicast enabled="true">-->
                <!--<multicast-group>235.1.1.1</multicast-group>-->
                <!--<multicast-port>2434</multicast-port>-->
            <!--</multicast>-->

            <!-- deactivate normal discovery -->
            <multicast enabled="false"/>
            <tcp-ip enabled="false" />

            <!-- activate the Kubernetes plugin -->
            <discovery-strategies>
                <discovery-strategy enabled="true"
                                    class="com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy">

                    <properties>
                        <!-- SERVICE-NAME.NAMESPACE.svc.cluster.local -->
                        <property name="service-dns">defined by env variable (hazelcast.kubernetes.service-dns)</property>
                        <property name="service-dns-timeout">500</property>
                    </properties>
                </discovery-strategy>
            </discovery-strategies>
        </join>
  </network>
```

### CODE REVIEW

**Comment by cschockaert** [comment]
hi @Jotschi 
can you include this lib in the pom,

tested in on a gke cluster, it's working fine
autodiscovery is ok via headless service dns:

here some log:


```
018-10-03 15:35:38:369 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Hazelcast 3.8.4 (20170809 - 297a77e) starting at [10.16.18.182]:5701 [system]
2018-10-03 15:35:38:369 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved. [system]
2018-10-03 15:35:38:369 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Configured Hazelcast Serialization version : 1 [system]
2018-10-03 15:35:38:561 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Backpressure is disabled [BackpressureRegulator]
2018-10-03 15:35:39:035 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Kubernetes Discovery properties: { service-dns: getmesh2-hazelcast.test-getmesh2.svc.cluster.local, service-dns-timeout: 500, service-name: null, service-port: 0, service-label: null, service-label-value: true, namespace: default, resolve-not-ready-addresses: false, kubernetes-master: https://kubernetes.default.svc} [DiscoveryService]
2018-10-03 15:35:39:044 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Kubernetes Discovery activated resolver: DnsEndpointResolver [DiscoveryService]
2018-10-03 15:35:39:045 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Activating Discovery SPI Joiner [Node]
2018-10-03 15:35:39:199 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Starting 1 partition threads [OperationExecutorImpl]
2018-10-03 15:35:39:200 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Starting 2 generic threads (1 dedicated for priority tasks) [OperationExecutorImpl]
2018-10-03 15:35:39:208 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] [10.16.18.182]:5701 is STARTING [LifecycleService]
2018-10-03 15:35:39:251 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Connecting to /10.16.9.240:5701, timeout: 0, bind-any: true [InitConnectionTask]
2018-10-03 15:35:39:262 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Established socket connection between /10.16.18.182:59601 and /10.16.9.240:5701 [TcpIpConnectionManager]
2018-10-03 15:35:40:262 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Accepting socket connection from /10.16.27.177:51015 [SocketAcceptorThread]
2018-10-03 15:35:40:263 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Established socket connection between /10.16.18.182:5701 and /10.16.27.177:51015 [TcpIpConnectionManager]
2018-10-03 15:35:40:268 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Cluster version set to 3.8 [system]
2018-10-03 15:35:40:270 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4]

Members [3] {
        Member [10.16.9.240]:5701 - 08db0089-abbc-44ba-aae5-ec5332ba837f
        Member [10.16.27.177]:5701 - d5ed0bc1-602d-4c2b-8e0a-5810d8f4014e
        Member [10.16.18.182]:5701 - 0c82cb58-9070-4308-96b6-19d16df1c186 this
}
 [ClusterService]
2018-10-03 15:35:41:159 WARNI [10.16.18.182]:5701 [default@65b328d9] [3.8.4] Master version should be greater than ours! Local version: 1773, Master version: 1772 Master: [10.16.9.240]:5701 [InternalPartitionService]
2018-10-03 15:35:42:273 INFO  [10.16.18.182]:5701 [default@65b328d9] [3.8.4] [10.16.18.182]:5701 is STARTED [LifecycleService]
2018-10-03 15:35:42:274 INFO  Starting distributed server 'getmesh2-replicas-1@0-24-1-SNAPSHOT' (hzID=0c82cb58-9070-4308-96b6-19d16df1c186)...
2018-10-03 15:35:42:279 INFO  Distributed cluster time=Wed Oct 03 15:35:42 GMT 2018 (delta from local node=1)...
2018-10-03 15:35:42:3
```

**Comment by Jotschi** [comment]
@cschockaert Thanks for the PR. I need to test this first in our k8s and check whether the size of the dependency is ok. Please give me some time to test this. I'm currently busy with other changes but I'll take a look at this as soon as I'm free.

**Comment by cschockaert** [comment]
ok, so whitout this lib, what autodiscovery method do you use in your K8s cluster?, mutlicast? direct member access?

**Comment by Jotschi** [comment]
@cschockaert Usually via direct members but that is not very elegant. I did not yet have time to test the k8s discovery. But it is good to hear that it works for you.

The lib is just 32kb and contains no transitive dependencies. I think I will add it to the server.

Another alternative to add the service would be:
```
mkdir lib
wget http://central.maven.org/maven2/com/hazelcast/hazelcast-kubernetes/1.3.1/hazelcast-kubernetes-1.3.1.jar -O lib/hazelcast-kubernetes-1.3.1.jar
docker run -v $PWD/lib:/mesh/lib --rm -it gentics/mesh java -cp /mesh/lib -jar mesh.jar
```

Would this solution also work for you? (Not tested)

**Pull request merged**
