### PR TITLE
Dev fix env image cache

### PR DESCRIPTION
**Pull request by karowin**
### General

* [ ] Added abstract that describes the change
* [ ] Added changelog entry to `/CHANGELOG.adoc`
* [ ] Ensured that the change is covered by tests
* [ ] Ensured that the change is documented in the docs

### On API Changes

* [ ] Checked if the changes are breaking or not
* [ ] Added GraphQL API if applicable
* [ ] Added Elasticsearch mapping if applicable

### CODE REVIEW

**Comment by karowin** [comment]
Do I need to build the code with all the test cases locally before pushing?

**Comment by Jotschi** [comment]
@karowin No. That would take way too long. As long as the `OptionsLoaderTest` is green that should be fine. Our jenkins will run the remaining tests.

**Comment by karowin** [comment]
Thanks @Jotschi for confirming.

**Comment by Jotschi** [comment]
@karowin I have merged the PR. Thanks for the PR. It will be included in the next version of Gentics Mesh.

**Pull request merged**
